Fix showing of component proptypes in storybook
lundegaard/lundium pull request #20
Opened 2020-02-21 13:33 UTC by vwerne

Closes #15

2020-02-26 11:47 UTC, MaceM8 approved these changes

2020-02-27 10:06 UTC, tommmyy requested changes

2020-02-27 10:06 UTC, tommmyy commented on babel.config.js
>  	return api.env('test')
Ternary can be removed.

2020-02-27 14:04 UTC, vwerne commented on babel.config.js
>  	return api.env('test')
done

2020-02-28 09:27 UTC, tommmyy approved these changes

2020-02-28 09:27 UTC, merged

2020-02-28 09:28 UTC, tommmyy commented
@vwerne great work!