LUN2 add: added basic project structure
lundegaard/lundium pull request #64
Opened 2021-10-08 14:58 UTC by mmaarrttyy

Basic LUN2 Project structure:

React app
React-docs app (Storybook)
Foundations app (cleaned CSP)
Lots of improvements are needed! Feel free to comment and come up with any ideas!

2021-10-11 09:12 UTC, jamescoq requested changes

2021-10-11 09:12 UTC, jamescoq commented on .eslintrc.js
> +				devDependencies: [
clean the project structure related configurations
For example I don't think we will have `api/**/*`. 
From my perspective it is better to add configuration than to have obsolete one.

2021-10-11 09:12 UTC, jamescoq commented on .gitignore
> +services/**/build
clean the project structure related configurations, we do not plan to have `modules/` or  `services/` etc.

2021-10-11 09:12 UTC, jamescoq commented on CHANGELOG.md
> +- [Build restructure, update dependencies](https://github.com/lundegaard/lundium/issues/16)
these are not relevant to this lundium version

2021-10-11 09:12 UTC, jamescoq commented on README.md
> +<h1 align="center">
this is not valid README, change or delete content

2021-10-11 09:12 UTC, jamescoq commented on VERSION_LOCKS.md
> +# Version locks
did we check if this is still valid ?

2021-10-11 09:12 UTC, jamescoq commented on apps/docs-react/package.json
> +		"@storybook/addon-actions": "^6.3.1",
upgrade all dependencies to the latest versions

2021-10-11 09:12 UTC, jamescoq commented on libs/react/rollup.config.js
> +import nodeResolve from 'rollup-plugin-node-resolve';
why are we using rollup here and webpack elsewhere? 
Webpack 5 has quite easy and straightforward configuration. I would suggest to use it.
see https://github.com/lundegaard/react-mapy-cz/blob/develop/webpack.config.js

2021-10-11 09:12 UTC, jamescoq commented on libs/react/package.json
> +{
should be adjusted if we use webpack instead of rollup

2021-10-11 14:41 UTC, mmaarrttyy commented on .eslintrc.js
> +				devDependencies: [
configuration updated

2021-10-11 14:41 UTC, mmaarrttyy commented on README.md
> +<h1 align="center">
content updated

2021-10-11 14:42 UTC, mmaarrttyy commented on .gitignore
> +services/**/build
obsolete modules removed

2021-10-11 14:42 UTC, mmaarrttyy commented on CHANGELOG.md
> +- [Build restructure, update dependencies](https://github.com/lundegaard/lundium/issues/16)
changelog cleaned

2021-10-11 14:42 UTC, mmaarrttyy commented on VERSION_LOCKS.md
> +# Version locks
version_locks cleaned

2021-10-11 14:43 UTC, mmaarrttyy commented on apps/docs-react/package.json
> +		"@storybook/addon-actions": "^6.3.1",
upgraded to 6.3.10

2021-10-11 14:43 UTC, mmaarrttyy commented on libs/react/rollup.config.js
> +import nodeResolve from 'rollup-plugin-node-resolve';
rollup removed, added webpack config

2021-10-11 14:53 UTC, tommmyy requested changes

2021-10-11 14:53 UTC, tommmyy commented on .editorconfig
> +# EditorConfig is awesome: https://editorconfig.org/
non standard - see current https://github.com/lundegaard/gatsby-theme-fast-ai/blob/master/.editorconfig

2021-10-11 14:53 UTC, tommmyy commented on .eslintrc.js
> +	plugins: ['react-hooks'],
not needed in new version https://github.com/lundegaard/gatsby-theme-fast-ai/blob/master/.eslintrc.js

2021-10-11 14:53 UTC, tommmyy commented on .prettierrc
> +{
recommendation https://github.com/lundegaard/gatsby-theme-fast-ai/blob/master/.prettierrc

2021-10-11 14:53 UTC, tommmyy commented on CONTRIBUTING.md
> +git merge upstream/master
we use "main"

2021-10-11 14:55 UTC, tommmyy commented on babel.config.js
> +			'babel-preset-react-union',
better use explicitly named plugins that are needed for the build of lundium. See facebook/react repo for inspiration

2021-10-11 14:55 UTC, tommmyy commented on libs/foundation/.browserslistrc
> +last 3 Edge versions
not sure why this is duplicated

2021-10-11 14:56 UTC, tommmyy commented on libs/foundation/README.md
> +2. Start config with `yarn setup`
I don't understand "Start config" phrase

2021-10-11 14:56 UTC, tommmyy commented on libs/foundation/README.md
> +3. Develop (`yarn start`)
why there are parenthesis?

2021-10-11 14:56 UTC, tommmyy commented on libs/foundation/README.md
> +### Required tools
Heading levels are messed up

2021-10-11 14:57 UTC, tommmyy commented on libs/foundation/README.md
> +* [Node] (http://nodejs.org) ^13.x
you should use package.json#engines for it AND .nvmrc

2021-10-11 15:00 UTC, tommmyy commented on libs/foundation/src/assets/images/icons/arrow-down.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg width="100%" height="100%" viewBox="0 0 12
move the assets to its own npm package

2021-10-11 15:00 UTC, tommmyy commented on libs/foundation/package.json
> +	"name": "@lundium/foundation",
I dont like the name... what means "foundation"? i cant see that this is "sass/css" project from the name at all.

2021-10-11 15:02 UTC, tommmyy commented on libs/foundation/webpack.config.js
> +// node modules
comments in this file are not much for a help

2021-10-11 15:03 UTC, tommmyy commented on libs/react/.babelrc
> +		"@babel/preset-react"
where are the es plugins?

2021-10-11 15:03 UTC, tommmyy commented on libs/react/package.json
> +	"scripts": {
we should move the building logic to the root of the monorepo

2021-10-12 12:04 UTC, mmaarrttyy commented on libs/react/package.json
> +	"scripts": {
Do you mean move webpack.config from /libs/react to the root of the monorepo?

2021-10-12 12:05 UTC, mmaarrttyy commented on libs/react/.babelrc
> +		"@babel/preset-react"
I think .babelrc file is not needed because of babel.config in project root... I'll remove it.

2021-10-12 12:22 UTC, mmaarrttyy commented on libs/foundation/package.json
> +	"name": "@lundium/foundation",
I thought we had agreed on the names of the packages -> https://wiki.lnd.bz/display/LUNDIUM/Architektura 🤔

2021-10-12 12:33 UTC, mmaarrttyy commented on libs/foundation/README.md
> +2. Start config with `yarn setup`
It's nonrelevant command from CSP, I'll remove it

2021-10-12 12:35 UTC, mmaarrttyy commented on CONTRIBUTING.md
> +git merge upstream/master
We don't have 'main' branch in lundium repo, but I expect it to be added in the future. I'll change it 👍🏼

2021-10-12 12:54 UTC, tommmyy commented on libs/react/package.json
> +	"scripts": {
i would do it. move the build logic to custom js script which would generate bundles. I always end up in this state. I start with simple weback.config and end up using rollup with CLI application above that with custom logic which arise as the project grows more complex.

recently I found this tool https://preconstruct.tools/ which would maybe help?

2021-10-12 12:55 UTC, tommmyy commented on libs/foundation/package.json
> +	"name": "@lundium/foundation",
hm... I am sure that I would not agree with this name

2021-10-12 12:55 UTC, tommmyy commented on libs/foundation/package.json
> +	"name": "@lundium/foundation",
@jamescoq

2021-10-12 13:51 UTC, jamescoq commented on libs/foundation/package.json
> +	"name": "@lundium/foundation",
foundation was suggested by @tomiikcz , I think he was getting inspired elsewhere.

2021-10-14 13:17 UTC, mmaarrttyy commented on libs/foundation/.browserslistrc
> +last 3 Edge versions
removed

2021-10-14 13:19 UTC, mmaarrttyy commented on libs/foundation/src/assets/images/icons/arrow-down.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg width="100%" height="100%" viewBox="0 0 12
I don't think it's needed right now. These are assets that are directly related to CSP, so it makes sense to leave them in the same package. If we decide that we want to have the assets separated, I will fix it in a separate PR.

2021-10-14 13:20 UTC, mmaarrttyy commented on libs/foundation/package.json
> +	"name": "@lundium/foundation",
so what about the package name?

2021-11-14 19:49 UTC, closed without merging